//GET ALL CATEGORIES
export const GET_CATEGORIES_LOADING="GET_CATEGORIES_LOADING"
export const GET_CATEGORIES_SUCCESS="GET_CATEGORIES_SUCCESS"
export const GET_CATEGORIES_ERROR="GET_CATEGORIES_ERROR"

// GET QUIZES CATEGORY
export const GET_QUIZZES_CATEGORY_LOADING="GET_QUIZZES_CATEGORY_LOADING"
export const GET_QUIZZES_CATEGORY_SUCCESS="GET_QUIZZES_CATEGORY_SUCCESS"
export const GET_QUIZZES_CATEGORY_ERROR="GET_QUIZZES_CATEGORY_ERROR"

// LOGIN
export const LOGIN_LOADING="LOGIN_LOADING"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_ERROR="LOGIN_ERROR"

// SIGNUP
export const SIGNUP_LOADING="SIGNUP_LOADING"
export const SIGNUP_SUCCESS="SIGNUP_SUCCESS"
export const SIGNUP_ERROR="SIGNUP_ERROR"

// DISCONNECT
export const DISCONNECT ="DISCONNECT"

// USER SEND ANSWER
export const SEND_ANSWER_LOADING="SEND_ANSWER__LOADING"
export const SEND_ANSWER_SUCCESS="SEND_ANSWER_SUCCESS"
export const SEND_ANSWER_ERROR="SEND_ANSWER_ERROR"
